### PR TITLE
Update to version 0.21.0

### PR DESCRIPTION
**Pull request by dorgan**

### CODE REVIEW

**Comment by ntodd** [comment]
Thanks for doing this, @dorgan. However, since 0.21.1 just came out, I bumped the version to that instead.

Thanks again!

**Comment by dorgan** [comment]
Docker hub still says last release was 9 months ago.

**Comment by dorgan** [comment]
0.21.2 released, but may want to update to latest HandBrakeCLI

**Comment by ntodd** [comment]
0.22.0 with updated dependencies is up on docker hub now.

**Pull request closed without merging**
